### ISSUE TITLE
Support latest version via official apt/rpm repos

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-postgresql#1]
See:
- https://wiki.postgresql.org/wiki/Apt
- https://wiki.postgresql.org/wiki/YUM_Installation

This might make the initial configuration a little easier, if I can target just one version (e.g. 9.5 or 9.6) instead of like 10 different versions :P

**Comment by madeinoz67** [comment]
Just tested on Centos 7.4 by adding the official repo as a pre_task and adding exclude=postgresql* in default CentOS-Base.repo as outlined in the YUM wiki link above.

official version gets installed however everything seems to get installed under  /usr/pgsql-x.x/ including bin and libs.   data is now under /var/lib/pgsql/x.x/data 

where x.x .is the official postgresql packaged version  

so is breaking the role.  I think the binary paths in the role will need to be exposed as role variables.

**Comment by AlexGluck** [comment]
Today i send PR for this role, and you can see, what all configuration what you need stay easy in place. And you get feature use "10 different versions" managed by variables for role. And #38 is duplicated for this issue.
