### ISSUE TITLE
Error when trying to initialize the DB

### ISSUE THREAD

**Issue by jbilbro** [geerlingguy/ansible-role-postgresql#10]
Using CentOS 7 with a Postgres 9.6 repo.  Trying to get it up and running but I keep getting tripped up on this step:

```
TASK [geerlingguy.postgresql : Ensure PostgreSQL database is initialized.] *****
fatal: [dc1-devops-db]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

Any idea what I'm doing wrong?

Using default pg OS user.

**Comment by geerlingguy** [comment]
It's saying your `sudo` use requires a password, so you'll need to supply the ansible remote user's sudo password when you run your playbook, e.g. by setting the `--ask-become-pass` (`-K` for short) flag on the command line. Then when you run the playbook, it will prompt you for your sudo password.

**Comment by jbilbro** [comment]
The confusing part is the user I'm running this as has full sudo with nopasswd and all other tasks before this run with no problems.

**Comment by jbilbro** [comment]
When I try with a sudo password for the remote_user I get the following error:

TASK [geerlingguy.postgresql : Ensure PostgreSQL databases are present.] *******
failed: [dc1-devops-db] (item={u'name': u'bamboo_db'}) => {"failed": true, "item": {"name": "bamboo_db"}, "module_stderr": "Sorry, user devops is not allowed to execute '/bin/sh -c echo BECOME-SUCCESS-ikltotafdcrssvxqdvbfruhgrxbsdgmf; /usr/bin/python' as postgres on dc1-devops-db.mbsbooks.com.\n", "module_stdout": "", "msg": "MODULE FAILURE"}

Note, if I SSH to the host as the remote_user and run sudo I am not prompted for a password.

**Comment by geerlingguy** [comment]
@jbilbro hmm... you may be running into https://github.com/ansible/ansible/issues/16048

**Comment by jbilbro** [comment]
Ah, this was my bad.  I misunderstood the line in sudoers.

I had:

> devops    ALL=NOPASSWD: ALL

but needed:

> devops  ALL=(ALL) NOPASSWD: ALL

to allow the devops user to run any command as any user instead of just as root.

**Comment by geerlingguy** [comment]
Great! Closing for now, then.
