### ISSUE TITLE
RedHat-2.yml not found when installing on Amazon Linux 2

### ISSUE THREAD

**Issue by Rightback** [geerlingguy/ansible-role-postgresql#102]
I'm trying to install PostgreSQL on Centos/Linux but I get "Could not find or access 'RedHat-2.yml' I go to ~/.ansible/roles/geerlingguy.postgresql/vars/ and I see RedHat-6.yml not RedHat-2.yml

**Comment by Rightback** [comment]
I fixed it my moving RedHat-6.yml to RedHat-2.yml
mv RedHat-6.yml RedHat-2.yml

**Comment by ganievs** [comment]
I have the same problem. The problem occurs when you try to install on AMZN Linux 2

**Comment by geerlingguy** [comment]
See related: https://github.com/geerlingguy/ansible-role-postgresql/pull/25

I don't 'officially' support Amazon Linux 2 in this role, however there is an `amazonlinux2` docker testing container this role can be tested against, if someone wants to make the vars file and add the test: https://github.com/geerlingguy/docker-amazonlinux2-ansible

**Comment by thoang2347** [comment]
Thanks @Rightback.  It works by 'mv RedHat-6.yml RedHat-2.yml'.  I also modified the postgresql_version to the version that I want.
