### ISSUE TITLE
Missing required package when using python3 (Ubuntu 16.04)

### ISSUE THREAD

**Issue by bkersten** [geerlingguy/ansible-role-postgresql#11]
When using role on Ubuntu Xenial with `ansible_python_interpreter` set to python3 the following error occurs due to missing package.

```
TASK [geerlingguy.postgresql : Ensure PostgreSQL databases are present.] *******
failed: [ubuntu-01] (item={u'name': u'app'}) => {"failed": true, "item": {"name": "app"}, "msg": "the python psycopg2 module is required"}
```

The task **Ensure PostgreSQL Python libraries are installed** installs `python-psycopg2` when `python3-psycopg2` is needed.

Workaround is to define `postgresql_packages` with inclusion of `python3-psycopg2`.

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/ansible-role-postgresql/search?utf8=✓&q=psycopg2&type=Code

One solution would be to make that requirement be configurable—e.g. turn that package name into a variable. I'd still default to the Python 2 version, but it would be easier to override for sure.

**Comment by geerlingguy** [comment]
On platforms like Fedora 30, which don't include Python 2 at all anymore, this default has been set to the python3 version explicitly: https://github.com/geerlingguy/ansible-role-postgresql/blob/531b23f8ec47cc9bfefaf3f707b0578a2e3f7c79/vars/Fedora-30.yml

I'm thinking we go that route (the default is set on OSes defaulting to Python 3) until Python 2 support has ended next year, then I'll change the default entirely, and just assume everyone's switching to a Python 3 interpreter on their managed servers.
