### ISSUE TITLE
Fix ansible-lint

### ISSUE THREAD

**Issue by rgarrigue** [geerlingguy/ansible-role-postgresql#116]
Hi there

I'm using ansible-lint with molecule to tests my role, relying on this one for quick postgres install. It's warning me about this

```
503 Tasks that run when changed should likely be handlers
/var/lib/jenkins/.ansible/roles/geerlingguy.postgresql/tasks/setup-Debian.yml:17
Task/Handler: Force-restart PostgreSQL after new locales are generated.
```

I'll get rid of it on my side ignoring the folder. But it could be fixed upstream with a `# noqa 503`. Do you mind adding it ?

Best regards,

**Comment by geerlingguy** [comment]
I detest that rule, so I've just ignored it globally on all my projects: https://github.com/geerlingguy/ansible-role-postgresql/blob/master/.ansible-lint

I recommend doing the same. See: https://github.com/ansible/ansible-lint/issues/419
