### ISSUE TITLE
Role doesn't work with Debian 7 (Unable to find 'Debian-7.yml')

### ISSUE THREAD

**Issue by roumano** [geerlingguy/ansible-role-postgresql#12]
the role ansible-role-postgresql it's failing on debian Wheezy : 
```
TASK [geerlingguy.postgresql : Include OS-specific variables (Debian).] ********
fatal: [wheezy]: FAILED! => {"ansible_facts": {}, "changed": false, "failed": true, "message": "Unable to find 'Debian-7.yml' in expected paths."}
```

i use the lastest version available : 
```
cat roles/geerlingguy.postgresql/meta/.galaxy_install_info
{install_date: 'Thu Mar 16 16:43:53 2017', version: 1.0.2}
```

It's true, on the file directory, it's not exist this version :  
```
ls roles/geerlingguy.postgresql/vars/
Debian-8.yml  RedHat-6.yml  RedHat-7.yml  Ubuntu-14.yml  Ubuntu-16.yml
```

**Comment by geerlingguy** [comment]
@roumano - While the role does state support for all versions of Debian (https://github.com/geerlingguy/ansible-role-postgresql/blob/master/meta/main.yml#L18), I actually haven't done any testing with Debian 7 / Wheezy (only Jessie). I don't have any servers running Wheezy anymore, so I won't work on adding support for it, but if it's something really simple (like adding a `Debian-7.yml` vars file) to get it working, I'd consider adding support.

**Comment by roumano** [comment]
With this files, it's working as expected Debian-7.yml : 
```
---
__postgresql_version: "9.1"
__postgresql_data_dir: "/var/lib/postgresql/{{ __postgresql_version }}/main"
__postgresql_bin_path: "/usr/lib/postgresql/{{ __postgresql_version }}/bin"
__postgresql_config_path: "/etc/postgresql/{{ __postgresql_version }}/main"
__postgresql_daemon: postgresql
__postgresql_packages:
  - postgresql
  - postgresql-contrib
  - libpq-dev
```

i have the take the Debian-8 files & update it with the version installed ...
