### ISSUE TITLE
 does not allow changing the collation on an existing DB, it only allows collation change on creation of db.

### ISSUE THREAD

**Issue by JensTimmerman** [geerlingguy/ansible-role-postgresql#147]
The taks `Ensure PostgreSQL databases are present.` fails on an existing database if the existing database has a different collation

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NotSupportedError: Changing LC_COLLATE is not supported. Current LC_COLLATE: C
failed: [gitea] (item={'name': 'gitea', 'owner': 'gitea'}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "gitea", "owner": "gitea"}, "msg": "Changing LC_COLLATE is not supported. Current LC_COLLATE: C"}
```

This is because postgress doesn't seem to allow to change the collaction on an existing database, only on creation time.

Could creation of a new database be skipped if it already exists?

**Comment by geerlingguy** [comment]
This seems like something that would best be solved by ensuring the database collation is managed by Ansible and would be accounted for in inventory. The `postgresql_db` module is meant to be idempotent.
