### ISSUE TITLE
Changing LC_COLLATE is not supported.

### ISSUE THREAD

**Issue by stam** [geerlingguy/ansible-role-postgresql#151]
The step "Ensure PostgreSQL databases are present" fails, even when not supplying a LC_COLLATE version.
Running on Ubuntu 20.04.1
PostgreSQL version 12.5

TASK [geerlingguy.postgresql : Ensure PostgreSQL databases are present.] **************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NotSupportedError: Changing LC_COLLATE is not supported. Current LC_COLLATE: C.UTF-8
failed: [server1] (item={'name': 'postgres', 'login_password': 'Deflator-Vocalist3', 'lc_collate': 'en_US.UTF-8', 'login_user': 'postgres', 'owner': 'postgres'}) => {"ansible_loop_var": "item", "changed": false, "item": {"lc_collate": "en_US.UTF-8", "login_password": "Deflator-Vocalist3", "login_user": "postgres", "name": "postgres", "owner": "postgres"}, "msg": "Changing LC_COLLATE is not supported. Current LC_COLLATE: C.UTF-8"}

**Comment by stam** [comment]
Nvm I'm dumb

**Comment by laurent-indermuehle** [comment]
In case someone falls into the same trap. I did find the problem:

This role uses a default with uppercase: default('en_US.UTF-8')
But  'template0' from PostgreSQL 10 uses lowercase :  en_US.utf-8

So if you created the database with the role, it's ok. But if the database was created from psql cli, you will encounter this error.
