### ISSUE TITLE
Migrating to collection

### ISSUE THREAD

**Issue by Timoses** [geerlingguy/ansible-role-postgresql#186]
Ansible is making the move towards Collections.

In order to use collections it appears that role dependencies (such as those towards this role) can no longer be resolved from collections.
Therefore, it is necessary to turn roles into collections in order to use them as collection dependencies.

Migration path is described here: https://docs.ansible.com/ansible/latest/dev_guide/migrating_roles.html
(The part stating "Update galaxy.yml to include any role dependencies." suggests it would be possible to install role dependencies from collections, however I did not find any possible way to achieve this as of yet).

Are there plans to move to a collection?

**Comment by Timoses** [comment]
Matter is not resolved yet.

**Comment by geerlingguy** [comment]
> Therefore, it is necessary to turn roles into collections in order to use them as collection dependencies.

I have a huge number of issues with collections still, and will not be moving any roles until there's a proper migration path for Galaxy role authors.

Closing this issue as I would rather make the change on a timeline I'm comfortable with, and so far there hasn't been as much activity around making role-to-collection migration easy (e.g. using same `geerlingguy.postgresql` namespace + name for the collection) as I'd like.
