### ISSUE TITLE
The role not install postgis?

### ISSUE THREAD

**Issue by mikysal78** [geerlingguy/ansible-role-postgresql#204]
I have testing on raspberry with debian 11 but postgis is not installed.

**Comment by derhuerst** [comment]
still relevant

**Comment by derhuerst** [comment]
still relevant

**Comment by derhuerst** [comment]
not stale

**Comment by robinportigliatti** [comment]
Hello,

No postgis is not installed.

If you want to install postgis, you will need to do it on your own and use `community.postgresql.postgresql_ext`.

Robin,
