### ISSUE TITLE
Unable to define global config with version 3.4.0

### ISSUE THREAD

**Issue by fblackburn1** [geerlingguy/ansible-role-postgresql#217]
Given I use the latest ansible-role-postgres (3.4.0)
Given I override `postgresql_global_config_options` variable (but not `log_directory` option)
When I execute my playbook
Then I get the following error:
```
TASK [geerlingguy.postgresql : Define postgresql_log_dir.] ************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'log_directory'\n\nThe error appears to be in '/root/.ansible
/roles/geerlingguy.postgresql/tasks/variables.yml': line 58, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Define po
stgresql_log_dir.\n  ^ here\n"}
```

Workaround: define `log_directory` inside my custom `postgresql_global_config_options` variable
Expected: No need to define `log_directory` option

Playbook:
```yaml
- name: Postgres issue
  hosts: test
  - name: Install postgres
    include_role:
      name: geerlingguy.postgresql
    vars:
      postgresql_global_config_options:
        - option: listen_addresses
          value: "{{ postgresql_listen_addresses | default('127.0.0.1') }}"
```

**Comment by dcardellino** [comment]
Same issue here

**Comment by Raptus1** [comment]
Same as @dcardellino here.

**Comment by hackingguy** [comment]
```
---
- hosts: db
  become: yes
  pre_tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes
  roles:
    - role: geerlingguy.postgresql
      vars:
        postgresql_users:
          - name: vagrant
            password: vagrant
        postgresql_databases:
          - name: books
            owner: vagrant
        postgresql_hba_entries:
          - { type: host, database: all, user: all, address: '0.0.0.0/0', auth_method: md5 }
        postgresql_global_config_options:
          - option: listen_addresses
            value: '*'
```

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/28388650/189498695-aa5a6699-b47a-4db2-ba0b-57d4b29fc750.png">

**Comment by crisrat** [comment]
> ```
> ---
> - hosts: db
>   become: yes
>   pre_tasks:
>     - name: Update repositories cache
>       apt:
>         update_cache: yes
>   roles:
>     - role: geerlingguy.postgresql
>       vars:
>         postgresql_users:
>           - name: vagrant
>             password: vagrant
>         postgresql_databases:
>           - name: books
>             owner: vagrant
>         postgresql_hba_entries:
>           - { type: host, database: all, user: all, address: '0.0.0.0/0', auth_method: md5 }
>         postgresql_global_config_options:
>           - option: listen_addresses
>             value: '*'
> ```
> 
> <img alt="image" width="1512" src="https://user-images.githubusercontent.com/28388650/189498695-aa5a6699-b47a-4db2-ba0b-57d4b29fc750.png">

I had the same issue, so just put the `log_directory` param in there as well, same value as the default
That seems to make it happy

**Comment by pavlozt** [comment]
Still actual

**Comment by pavlozt** [comment]
> > Still actual
> 
> indeed check my solution above, perhaps it works for you as well

Of course, I have no problem finding the workaround. 
This issue should be investigated and fixed in this repository.

**Comment by cristianrat** [comment]
I agree :)

**Comment by Raptus1** [comment]
Hi,

You are missing the log_directory variable that you can find under defaults:

postgresql_global_config_options:
- option: unix_socket_directories
value: '{{ postgresql_unix_socket_directories | join(",") }}'
- option: log_directory
value: 'log'

If you override the postgresql_global_config_options variable, you will
need to also include the log_directory and it's value

**Comment by charlfields** [comment]
After adding the option: log_directory, it kinda works! I get the following error and I need to restart postgresql manually
TASK [geerlingguy.postgresql : Ensure PostgreSQL users are present.] *****************************************************
failed: [208.83.232.178] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
fatal: [208.83.232.178]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}

**Comment by unencoded** [comment]
[charlfields](https://github.com/charlfields) I have the same problem.

**Comment by shamilovstas** [comment]
The issue is still there
