### ISSUE TITLE
Error Initializing Database

### ISSUE THREAD

**Issue by pyrodie18** [geerlingguy/ansible-role-postgresql#218]
When running the role, I receive an error on step `TASK [geerlingguy.postgresql : Ensure PostgreSQL database is initialized.] `

**Ansible Information**
```
[root@localhost devel]# ansible --version
ansible [core 2.12.2]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.7 (default, Sep 21 2021, 00:13:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.0.3
  libyaml = True
```

**Playbook**
```
- name: Install Database
  hosts: rocky-8

  roles:
    - role: geerlingguy.postgresql
      become: true
```

**Play Output**
```
TASK [geerlingguy.postgresql : Ensure PostgreSQL database is initialized.] ***********
fatal: [rocky-8]: FAILED! => {
    "changed": true,
    "cmd": [
        "/usr/bin/initdb",
        "-D",
        "/var/lib/pgsql/data"
    ],
    "delta": "0:00:00.013172",
    "end": "2022-07-31 09:29:09.997343",
    "invocation": {
        "module_args": {
            "_raw_params": "/usr/bin/initdb -D /var/lib/pgsql/data",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": false
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2022-07-31 09:29:09.984171",
    "stderr": "initdb: cannot be run as root\nPlease log in (using, e.g., \"su\") as the (unprivileged) user that will\nown the server process.",
    "stderr_lines": [
        "initdb: cannot be run as root",
        "Please log in (using, e.g., \"su\") as the (unprivileged) user that will",
        "own the server process."
    ],
    "stdout": "",
    "stdout_lines": []
}

```

**Comment by mmekut** [comment]
That's strange as the task uses become to run as the user that owns the server process......
Here is the code...
`- name: Ensure PostgreSQL database is initialized.
  command: "{{ postgresql_bin_path }}/initdb -D {{ postgresql_data_dir }}"
  when: not pgdata_dir_version.stat.exists
  become: true
  become_user: "{{ postgresql_user }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true`

1. If this is not the first time you are running the role, remove PG_Data directory manually.
2. Download a fresh version of the role.
3. You can initialize Postgresql manually (though it isn't desirable) using the command below:
    `sudo {{postgresql_user}} initdb -D /var/lib/pgsql/data`  where {{postgresql_user}} is the user that owns postgresql server

**Comment by fhsctv** [comment]
@pyrodie18 
If you write` become: true` without defining the `become_user`, then the user is set to `root`.
you cannot init a db as root
so you may add `become_user: "{{ postgresql_user }}"` to your playbook.
