### ISSUE TITLE
Installs version specified by default postgres_version variable on AlmaLinux 8.6

### ISSUE THREAD

**Issue by mmekut** [geerlingguy/ansible-role-postgresql#219]
Before running this role as root, I had a custom role setup official Postgresql 13 repo on AlmaLinux 8.6 since i didn't
want to use the default streams provided by the OS which is a vagrant box.

This role does not use the repo specified by the variable {{postgresql_enablerepo}} despite being set in my variable file, instead it installs from the default enabled stream from OS appstream repo.

It also does not use the version specified by {{postgresql_version}} in my variable file even when the version is available from the OS appstream repo.

The role only installs the postgresql version specified in the default variable file that comes with the role (i.e version 10).

@geerlingguy has an ansible module been created for enabling/disabling dnf modules?

**Comment by Bigsmooth68** [comment]
I am not sure if it is wanted behavior, but it uses only default enabled repo from within the OS.

It does not add/enable external repos and it does not adapt command and data path to the installed PG version.

**Comment by mmekut** [comment]
By design it is unwanted, but the behaviors were _"mistakenly"_ hardcoded into the codebase instead of using role variables defined in the variables file.

I corrected the behavior by forking the codebase, unfortunately i haven't committed the modified codebase yet.

Hopefully I will create a pull request when i commit
