### ISSUE TITLE
pg_ident.conf support

### ISSUE THREAD

**Issue by arhue** [geerlingguy/ansible-role-postgresql#220]
Issue https://github.com/geerlingguy/ansible-role-postgresql/issues/61 was closed, but this is an important feature.

**Comment by greyhare** [comment]
I need this feature on a machine I have (I use local mapping and have to map the gitlab-runner user to a different name because it has a dash). I guess I can write the file with a template elsewhere, but it would be nice to have all the postgresql configuration here.
