### ISSUE TITLE
postgresql daemon is not properly set for debian9 (9.6)

### ISSUE THREAD

**Issue by idanshimon** [geerlingguy/ansible-role-postgresql#23]
postgres (9.6 on debian 9) service should be enabled according to the version it is installed otherwise you would probably get an "empty" service template for systemd 

the **incorrect** command is 

    vagrant@debhost:~$ sudo systemctl enable postgresql
    Synchronizing state of postgresql.service with SysV service script with /lib/systemd/systemd-sysv-install.
    Executing: /lib/systemd/systemd-sysv-install enable postgresql
    vagrant@debhost:~$ sudo systemctl status postgresql
    ● postgresql.service - PostgreSQL RDBMS
       Loaded: loaded (/lib/systemd/system/postgresql.service; enabled; vendor preset: enabled)
       Active: active (exited) since Tue 2017-08-08 11:12:27 UTC; 3min 3s ago
     Main PID: 10028 (code=exited, status=0/SUCCESS)
    
    Aug 08 11:12:27 debhost systemd[1]: Starting PostgreSQL RDBMS...
    Aug 08 11:12:27 debhost systemd[1]: Started PostgreSQL RDBMS.
    vagrant@debhost:~$ cat /lib/systemd/system/postgresql.service
    # systemd service for managing all PostgreSQL clusters on the system. This
    # service is actually a systemd target, but we are using a service since
    # targets cannot be reloaded.
    
    [Unit]
    Description=PostgreSQL RDBMS
    
    [Service]
    Type=oneshot
    ExecStart=/bin/true
    ExecReload=/bin/true
    RemainAfterExit=on
    
    [Install]
    WantedBy=multi-user.target

The correct command should be

    vagrant@debhost:~$ sudo systemctl enable postgresql@9.6-main
    vagrant@debhost:~$ sudo systemctl status postgresql@9.6-main
    ● postgresql@9.6-main.service - PostgreSQL Cluster 9.6-main
       Loaded: loaded (/lib/systemd/system/postgresql@.service; enabled; vendor preset: enabled)
       Active: active (running) since Tue 2017-08-08 11:12:27 UTC; 4min 22s ago
     Main PID: 10010 (postgres)
       CGroup: /system.slice/system-postgresql.slice/postgresql@9.6-main.service
               ├─10010 /usr/lib/postgresql/9.6/bin/postgres -D /var/lib/postgresql/9.6/main -c config_file=/etc/postgresql/9.6/main/postgresql.conf
               ├─10012 postgres: 9.6/main: checkpointer process
               ├─10013 postgres: 9.6/main: writer process
               ├─10014 postgres: 9.6/main: wal writer process
               ├─10015 postgres: 9.6/main: autovacuum launcher process
               ├─10016 postgres: 9.6/main: stats collector process
               └─10017 postgres: 9.6/main: user postgres 192.168.33.1(12512) idle
    
    Aug 08 11:12:25 debhost systemd[1]: Stopped PostgreSQL Cluster 9.6-main.
    Aug 08 11:12:25 debhost systemd[1]: Starting PostgreSQL Cluster 9.6-main...
    Aug 08 11:12:27 debhost systemd[1]: Started PostgreSQL Cluster 9.6-main.
    vagrant@debhost:~$ cat /lib/systemd/system/postgresql
    postgresql.service   postgresql@.service
    vagrant@debhost:~$ cat /lib/systemd/system/postgresql@.service
    # systemd service template for PostgreSQL clusters. The actual instances will
    # be called "postgresql@version-cluster", e.g. "postgresql@9.3-main". The
    # variable %i expands to "version-cluster", %I expands to "version/cluster".
    # (%I breaks for cluster names containing dashes.)
    
    [Unit]
    Description=PostgreSQL Cluster %i
    ConditionPathExists=/etc/postgresql/%I/postgresql.conf
    PartOf=postgresql.service
    ReloadPropagatedFrom=postgresql.service
    Before=postgresql.service
    
    [Service]
    Type=forking
    # @: use "postgresql@%i" as process name
    ExecStart=@/usr/bin/pg_ctlcluster postgresql@%i --skip-systemctl-redirect %i start
    ExecStop=/usr/bin/pg_ctlcluster --skip-systemctl-redirect -m fast %i stop
    ExecReload=/usr/bin/pg_ctlcluster --skip-systemctl-redirect %i reload
    PIDFile=/var/run/postgresql/%i.pid
    SyslogIdentifier=postgresql@%i
    # prevent OOM killer from choosing the postmaster (individual backends will
    # reset the score to 0)
    OOMScoreAdjust=-900
    # restarting automatically will prevent "pg_ctlcluster ... stop" from working,
    # so we disable it here. Also, the postmaster will restart by itself on most
    # problems anyway, so it is questionable if one wants to enable external
    # automatic restarts.
    #Restart=on-failure
    # (This should make pg_ctlcluster stop work, but doesn't:)
    #RestartPreventExitStatus=SIGINT SIGTERM
    
    [Install]
    WantedBy=multi-user.target

the ansible role defines a handler to restart postgresql however it is using the postgres_daemon var which is set incorrectly therefore giving false indication for database service restart, see below: 

    RUNNING HANDLER [geerlingguy.postgresql : restart postgresql] ********************************************************************************************************************************
    
    
     [WARNING]: Ignoring "sleep" as it is not used in "systemd"
    
    Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/system/systemd.py
    <192.168.33.50> ESTABLISH SSH CONNECTION FOR USER: vagrant
    <192.168.33.50> SSH: EXEC sshpass -d12 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=vagrant -o ConnectTimeout=10 -o ControlPath=/home/vagrant/.ansib
    
    le/cp/673d2d4c12 192.168.33.50 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-dpuxjcyqgnwvajepusmhaselfsacbhku; /usr/bin/python'"'"'"'"'"'"'"'"' && sl
    
    eep 0'"'"''
    **<192.168.33.50> (0, '\n{"status": {"ExecStart": "{ path=/bin/true ; argv[]=/bin/true ; ignore_errors=no ; start_time=[Tue 2017-08-08 11:01:49 UTC] ; stop_time=[Tue 2017-08-08 11:01:49 UTC] ;**
    
     pid=9860 ; code=exited ; status=0 }", "TimeoutStopUSec": "1min 30s", "RuntimeDirectoryMode": "0755", "GuessMainPID": "yes", "ActiveExitTimestamp": "Tue 2017-08-08 11:01:46 UTC", "ExecMainCo
    
    de": "1", "PropagatesReloadTo": "postgresql@9.6-main.service", "ExecMainPID": "9860", "LimitSIGPENDING": "1878", "MemoryHigh": "18446744073709551615", "OOMScoreAdjust": "0", "LoadState": "lo
    
    aded", "UID": "4294967295", "ProtectHome": "no", "RuntimeMaxUSec": "infinity", "TTYVHangup": "no", "WatchdogTimestampMonotonic": "0", "LimitMSGQUEUESoft": "819200", "LimitSTACK": "1844674407
    
    3709551615", "MemorySwapMax": "18446744073709551615", "ActiveEnterTimestampMonotonic": "1763252353", "StandardError": "inherit", "CanIsolate": "no", "LimitDATASoft": "18446744073709551615",
    "GID": "4294967295", "CPUSchedulingPriority": "0", "KillSignal": "15", "LimitFSIZE": "18446744073709551615", "IgnoreOnIsolate": "no", "LimitCPU": "18446744073709551615", "AssertTimestamp": "
    
    Tue 2017-08-08 11:01:49 UTC", "RemoveIPC": "no", "CPUUsageNSec": "18446744073709551615", "LimitNICESoft": "0", "LimitMEMLOCKSoft": "65536", "UnitFileState": "enabled", "NoNewPrivileges": "no
    
    ", "MemoryLimit": "18446744073709551615", "MemoryDenyWriteExecute": "no", "InvocationID": "24928b8fde164fa8987ff78cfc47eb01", "CanStart": "yes", "IOAccounting": "no", "JobTimeoutAction": "no
    
    ne", "Before": "multi-user.target exim4.service shutdown.target", "LimitAS": "18446744073709551615", "SyslogLevel": "6", "RootDirectoryStartOnly": "no", "InactiveExitTimestampMonotonic": "17
    
    63248168", "SendSIGHUP": "no", "TimeoutStartUSec": "infinity", "Type": "oneshot", "FailureAction": "none", "SameProcessGroup": "no", "LimitNPROC": "1878", "UMask": "0022", "NonBlocking": "no
    
    ", "DevicePolicy": "auto", "ProtectKernelTunables": "no", "ExecMainStartTimestamp": "Tue 2017-08-08 11:01:49 UTC", "LimitRSSSoft": "18446744073709551615", "CapabilityBoundingSet": "184467440
    
    73709551615", "TTYReset": "no", "FileDescriptorStoreMax": "0", "RefuseManualStart": "no", "KillMode": "control-group", "SyslogLevelPrefix": "yes", "LimitRSS": "18446744073709551615", "LimitR
    
    TPRIO": "0", "StartupCPUWeight": "18446744073709551615", "Delegate": "no", "MemoryMax": "18446744073709551615", "ExecReload": "{ path=/bin/true ; argv[]=/bin/true ; ignore_errors=no ; start_
    
    time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }", "SyslogFacility": "3", "TasksCurrent": "18446744073709551615", "InactiveExitTimestamp": "Tue 2017-08-08 11:01:49 UTC", "Li
    
    mitCORE": "18446744073709551615", "JobTimeoutUSec": "infinity", "TimerSlackNSec": "50000", "StateChangeTimestamp": "Tue 2017-08-08 11:01:49 UTC", "SubState": "exited", "CPUSchedulingResetOnF
    
    ork": "no", "Result": "success", "CPUShares": "18446744073709551615", "LimitCORESoft": "0", "ConditionResult": "yes", "NFileDescriptorStore": "0", "LimitNOFILESoft": "1024", "TTYVTDisallocat
    
    e": "no", "MainPID": "0", "StartupBlockIOWeight": "18446744073709551615", "ActiveEnterTimestamp": "Tue 2017-08-08 11:01:49 UTC", "FragmentPath": "/lib/systemd/system/postgresql.service", "Li
    
    mitSIGPENDINGSoft": "1878", "ProtectControlGroups": "no", "StartupCPUShares": "18446744073709551615", "WatchdogUSec": "0", "ActiveState": "active", "Nice": "0", "LimitDATA": "184467440737095
    
    51615", "UnitFilePreset": "enabled", "LimitNPROCSoft": "1878", "MemoryCurrent": "18446744073709551615", "LimitRTTIME": "18446744073709551615", "WantedBy": "multi-user.target", "SecureBits":
    "0", "RestartUSec": "100ms", "ConditionTimestamp": "Tue 2017-08-08 11:01:49 UTC", "CPUAccounting": "no", "RemainAfterExit": "yes", "PrivateUsers": "no", "PrivateNetwork": "no", "StartupIOWei
    
    ght": "18446744073709551615", "Restart": "no", "CPUSchedulingPolicy": "0", "LimitNOFILE": "4096", "SendSIGKILL": "yes", "StatusErrno": "0", "RefuseManualStop": "no", "SystemCallErrorNumber":
    
     "0", "MemoryLow": "0", "Perpetual": "no", "IOWeight": "18446744073709551615", "LimitCPUSoft": "18446744073709551615", "TasksAccounting": "yes", "NeedDaemonReload": "no", "ExecMainExitTimest
    
    amp": "Tue 2017-08-08 11:01:49 UTC", "InactiveEnterTimestamp": "Tue 2017-08-08 11:01:46 UTC", "StandardInput": "null", "AssertTimestampMonotonic": "1763247726", "DefaultDependencies": "yes",
    
     "Requires": "sysinit.target system.slice", "UtmpMode": "init", "StateChangeTimestampMonotonic": "1763252353", "TasksMax": "4915", "CPUQuotaPerSecUSec": "infinity", "ExecMainStatus": "0", "L
    
    imitMEMLOCK": "65536", "StopWhenUnneeded": "no", "LimitMSGQUEUE": "819200", "LimitRTPRIOSoft": "0", "LimitSTACKSoft": "8388608", "CPUWeight": "18446744073709551615", "AmbientCapabilities": "
    
    0", "AllowIsolate": "no", "Slice": "system.slice", "ExecMainExitTimestampMonotonic": "1763252196", "ConsistsOf": "postgresql@9.6-main.service", "LimitFSIZESoft": "18446744073709551615", "Sta
    
    rtLimitIntervalSec": "10000000", "NotifyAccess": "none", "PermissionsStartOnly": "no", "BlockIOAccounting": "no", "CanStop": "yes", "PrivateTmp": "no", "OnFailureJobMode": "replace", "Assert
    
    Result": "yes", "LimitLOCKS": "18446744073709551615", "ExecMainStartTimestampMonotonic": "1763248143", "StartLimitBurst": "5", "Wants": "postgresql@9.6-main.service", "After": "systemd-journ
    
    ald.socket system.slice basic.target postgresql@9.6-main.service sysinit.target", "ProtectKernelModules": "no", "SyslogPriority": "30", "StartLimitAction": "none", "Conflicts": "shutdown.tar
    
    get", "RestrictNamespace": "2114060288", "StandardOutput": "journal", "MountFlags": "0", "InactiveEnterTimestampMonotonic": "1760095277", "MemoryAccounting": "no", "IgnoreSIGPIPE": "yes", "T
    
    ransient": "no", "IOScheduling": "0", "Description": "PostgreSQL RDBMS", "DynamicUser": "no", "ActiveExitTimestampMonotonic": "1760095277", "RestrictRealtime": "no", "CanReload": "yes", "Con
    
    trolPID": "0", "LimitNICE": "0", "BlockIOWeight": "18446744073709551615", "LimitLOCKSSoft": "18446744073709551615", "LimitRTTIMESoft": "18446744073709551615", "Names": "postgresql.service",
    "ProtectSystem": "no", "LimitASSoft": "18446744073709551615", "PrivateDevices": "no", "Id": "postgresql.service", "ConditionTimestampMonotonic": "1763247726"}, "invocation": {"module_args":
    {"no_block": false, "name": "postgresql", "enabled": null, "daemon_reload": false, "state": "restarted", "user": false, "masked": null}}, "state": "started", "changed": true, "name": "postgr
    
    esql"}\n', '')
    changed: [postgresql001] => {
        "changed": true, 
        "invocation": {
            "module_args": {
                "daemon_reload": false, 
                "enabled": null, 
                "masked": null, 
                "name": "postgresql", 
                "no_block": false, 
                "state": "restarted", 
                "user": false
            }
        }, 
        "name": "postgresql", 
        "state": "started", 
        "status": {
            "ActiveEnterTimestamp": "Tue 2017-08-08 11:01:49 UTC", 
            "ActiveEnterTimestampMonotonic": "1763252353", 
            "ActiveExitTimestamp": "Tue 2017-08-08 11:01:46 UTC", 
            "ActiveExitTimestampMonotonic": "1760095277", 
            "ActiveState": "active", 
            "After": "systemd-journald.socket system.slice basic.target postgresql@9.6-main.service sysinit.target", 
            "AllowIsolate": "no", 
            "AmbientCapabilities": "0", 
            "AssertResult": "yes", 
            "AssertTimestamp": "Tue 2017-08-08 11:01:49 UTC", 
            "AssertTimestampMonotonic": "1763247726", 
            "Before": "multi-user.target exim4.service shutdown.target", 
            "BlockIOAccounting": "no", 
            "BlockIOWeight": "18446744073709551615", 
            "CPUAccounting": "no", 
            "CPUQuotaPerSecUSec": "infinity", 
            "CPUSchedulingPolicy": "0", 
            "CPUSchedulingPriority": "0", 
            "CPUSchedulingResetOnFork": "no", 
            "CPUShares": "18446744073709551615", 
            "CPUUsageNSec": "18446744073709551615", 
            "CPUWeight": "18446744073709551615", 
            "CanIsolate": "no", 
            "CanReload": "yes", 
            "CanStart": "yes", 
            "CanStop": "yes", 
            "CapabilityBoundingSet": "18446744073709551615", 
            "ConditionResult": "yes", 
            "ConditionTimestamp": "Tue 2017-08-08 11:01:49 UTC", 
            "ConditionTimestampMonotonic": "1763247726", 
            "Conflicts": "shutdown.target", 
            "ConsistsOf": "postgresql@9.6-main.service", 
            "ControlPID": "0", 
            "DefaultDependencies": "yes", 
            "Delegate": "no", 
            "Description": "PostgreSQL RDBMS", 
            "DevicePolicy": "auto", 
            "DynamicUser": "no", 
            "ExecMainCode": "1", 
            "ExecMainExitTimestamp": "Tue 2017-08-08 11:01:49 UTC", 
            "ExecMainExitTimestampMonotonic": "1763252196", 
            "ExecMainPID": "9860", 
            "ExecMainStartTimestamp": "Tue 2017-08-08 11:01:49 UTC", 
            "ExecMainStartTimestampMonotonic": "1763248143", 
            "ExecMainStatus": "0", 
            "ExecReload": "{ path=/bin/true ; argv[]=/bin/true ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }", 
            "ExecStart": "{ path=/bin/true ; argv[]=/bin/true ; ignore_errors=no ; start_time=[Tue 2017-08-08 11:01:49 UTC] ; stop_time=[Tue 2017-08-08 11:01:49 UTC] ; pid=9860 ; code=exited ; s
    
    tatus=0 }",
            "FailureAction": "none", 
            "FileDescriptorStoreMax": "0", 
            "FragmentPath": "/lib/systemd/system/postgresql.service", 
            "GID": "4294967295", 
            "GuessMainPID": "yes", 
            "IOAccounting": "no", 
            "IOScheduling": "0", 
            "IOWeight": "18446744073709551615", 
            "Id": "postgresql.service", 
            "IgnoreOnIsolate": "no", 
            "IgnoreSIGPIPE": "yes", 
            "InactiveEnterTimestamp": "Tue 2017-08-08 11:01:46 UTC", 
            "InactiveEnterTimestampMonotonic": "1760095277", 
            "InactiveExitTimestamp": "Tue 2017-08-08 11:01:49 UTC", 
            "InactiveExitTimestampMonotonic": "1763248168", 
            "InvocationID": "24928b8fde164fa8987ff78cfc47eb01", 
            "JobTimeoutAction": "none", 
            "JobTimeoutUSec": "infinity", 
            "KillMode": "control-group", 
            "KillSignal": "15", 
            "LimitAS": "18446744073709551615", 
            "LimitASSoft": "18446744073709551615", 
            "LimitCORE": "18446744073709551615", 
            "LimitCORESoft": "0", 
            "LimitCPU": "18446744073709551615", 
            "LimitCPUSoft": "18446744073709551615", 
            "LimitDATA": "18446744073709551615", 
            "LimitDATASoft": "18446744073709551615", 
            "LimitFSIZE": "18446744073709551615", 
            "LimitFSIZESoft": "18446744073709551615", 
            "LimitLOCKS": "18446744073709551615", 
            "LimitLOCKSSoft": "18446744073709551615", 
            "LimitMEMLOCK": "65536", 
            "LimitMEMLOCKSoft": "65536", 
            "LimitMSGQUEUE": "819200", 
            "LimitMSGQUEUESoft": "819200", 
            "LimitNICE": "0", 
            "LimitNICESoft": "0", 
            "LimitNOFILE": "4096", 
            "LimitNOFILESoft": "1024", 
            "LimitNPROC": "1878", 
            "LimitNPROCSoft": "1878", 
            "LimitRSS": "18446744073709551615", 
            "LimitRSSSoft": "18446744073709551615", 
            "LimitRTPRIO": "0", 
            "LimitRTPRIOSoft": "0", 
            "LimitRTTIME": "18446744073709551615", 
            "LimitRTTIMESoft": "18446744073709551615", 
            "LimitSIGPENDING": "1878", 
            "LimitSIGPENDINGSoft": "1878", 
            "LimitSTACK": "18446744073709551615", 
            "LimitSTACKSoft": "8388608", 
            "LoadState": "loaded", 
            "MainPID": "0", 
            "MemoryAccounting": "no", 
            "MemoryCurrent": "18446744073709551615", 
            "MemoryDenyWriteExecute": "no", 
            "MemoryHigh": "18446744073709551615", 
            "MemoryLimit": "18446744073709551615", 
            "MemoryLow": "0", 
            "MemoryMax": "18446744073709551615", 
            "MemorySwapMax": "18446744073709551615", 
            "MountFlags": "0", 
            "NFileDescriptorStore": "0", 
            "Names": "postgresql.service", 
            "NeedDaemonReload": "no", 
            "Nice": "0", 
            "NoNewPrivileges": "no", 
            "NonBlocking": "no", 
            "NotifyAccess": "none", 
            "OOMScoreAdjust": "0", 
            "OnFailureJobMode": "replace", 
            "PermissionsStartOnly": "no", 
            "Perpetual": "no", 
            "PrivateDevices": "no", 
            "PrivateNetwork": "no", 
            "PrivateTmp": "no", 
            "PrivateUsers": "no", 
            "PropagatesReloadTo": "postgresql@9.6-main.service", 
            "ProtectControlGroups": "no", 
            "ProtectHome": "no", 
            "ProtectKernelModules": "no", 
            "ProtectKernelTunables": "no", 
            "ProtectSystem": "no", 
            "RefuseManualStart": "no", 
            "RefuseManualStop": "no", 
            "RemainAfterExit": "yes", 
            "RemoveIPC": "no", 
            "Requires": "sysinit.target system.slice", 
            "Restart": "no", 
            "RestartUSec": "100ms", 
            "RestrictNamespace": "2114060288", 
            "RestrictRealtime": "no", 
            "Result": "success", 
            "RootDirectoryStartOnly": "no", 
            "RuntimeDirectoryMode": "0755", 
            "RuntimeMaxUSec": "infinity", 
            "SameProcessGroup": "no", 
            "SecureBits": "0", 
            "SendSIGHUP": "no", 
            "SendSIGKILL": "yes", 
            "Slice": "system.slice", 
            "StandardError": "inherit", 
            "StandardInput": "null", 
            "StandardOutput": "journal", 
            "StartLimitAction": "none", 
            "StartLimitBurst": "5", 
            "StartLimitIntervalSec": "10000000", 
            "StartupBlockIOWeight": "18446744073709551615", 
            "StartupCPUShares": "18446744073709551615", 
            "StartupCPUWeight": "18446744073709551615", 
            "StartupIOWeight": "18446744073709551615", 
            "StateChangeTimestamp": "Tue 2017-08-08 11:01:49 UTC", 
            "StateChangeTimestampMonotonic": "1763252353", 
            "StatusErrno": "0", 
            "StopWhenUnneeded": "no", 
            "SubState": "exited", 
            "SyslogFacility": "3", 
            "SyslogLevel": "6", 
            "SyslogLevelPrefix": "yes", 
            "SyslogPriority": "30", 
            "SystemCallErrorNumber": "0", 
            "TTYReset": "no", 
            "TTYVHangup": "no", 
            "TTYVTDisallocate": "no", 
            "TasksAccounting": "yes", 
            "TasksCurrent": "18446744073709551615", 
            "TasksMax": "4915", 
            "TimeoutStartUSec": "infinity", 
            "TimeoutStopUSec": "1min 30s", 
            "TimerSlackNSec": "50000", 
            "Transient": "no", 
            "Type": "oneshot", 
            "UID": "4294967295", 
            "UMask": "0022", 
            "UnitFilePreset": "enabled", 
            "UnitFileState": "enabled", 
            "UtmpMode": "init", 
            "WantedBy": "multi-user.target", 
            "Wants": "postgresql@9.6-main.service", 
            "WatchdogTimestampMonotonic": "0", 
            "WatchdogUSec": "0"
        }
    }
    META: ran handlers

**Comment by idanshimon** [comment]
I discovered this issue after this error msg:

> msg: unable to connect to database: FATAL:  Peer authentication failed for user "postgres"

After checking my pg_hba configuration and seeing nothing was wrong with that i started to suspect the ansible role parameters. I've done the process manually and noticed the service is never really restarted.

This is the root cause for a lot of users who have Peer authentication error for default user postgres even after setting postgres user as "trust" i(pg_hba file). Since the role cannot restart the database the pg_hba settings file is never applied !

To workaround this issue simply set the following vars:

```
vars:
    postgresql_version: "9.6"
    postgresql_daemon: "postgresql@{{ postgresql_version }}-main"

```

I hope this post can help others

**Comment by tavinus** [comment]
This also applies to Debian Jessie with Postgres9.4.
On the few times we had reboots the postgres server did not come back.
Can't reboot right now but I enabled the @9.4 service with:
```
sudo systemctl enable postgresql@9.4-main.service
```

**Comment by AlexGluck** [comment]
Tomorrow i check this issue and PR with fix. Thx

**Comment by AlexGluck** [comment]
I done fix for this in PR #47

**Comment by AlexGluck** [comment]
Fix done in PR #47

**Comment by geerlingguy** [comment]
Testing a fix locally for Debian 8/9.

**Comment by DanielJulian** [comment]
THANK YOU SO MUCH!! Having this issue with postgresql-11 in ubuntu 18
