### ISSUE TITLE
Fedora 37

### ISSUE THREAD

**Issue by TheFieryLynx** [geerlingguy/ansible-role-postgresql#238]
Hello! When is fedora 37 support expected?

**Comment by yodatak** [comment]
And now 38 too :/ are you open for PR @geerlingguy  ?

**Comment by geerlingguy** [comment]
Yes, open for that — please ping me if you have a PR that you can add in testing and update it to fedora38 on the CI image!

**Comment by geerlingguy** [comment]
(I am pushing a new Docker test image to https://hub.docker.com/repository/docker/geerlingguy/docker-fedora38-ansible/general)
