### ISSUE TITLE
postgresql_users roles member predefined

### ISSUE THREAD

**Issue by KaMaToZzz** [geerlingguy/ansible-role-postgresql#239]
Hello,

How adding user and grant him predefined roles membership, like: https://www.postgresql.org/docs/current/predefined-roles.html#PREDEFINED-ROLES-TABLE ?

**Comment by geerlingguy** [comment]
TBH, I am not running any servers running postgres personally right now, so this role has been a bit lower on my priority list... that said, if someone would like to work on making sure it transitions to the new version correctly, I'd be willing to merge a well-tested update!
