### ISSUE TITLE
Documentation for priv attribute of postgresql_users parameter

### ISSUE THREAD

**Issue by w4rdy** [geerlingguy/ansible-role-postgresql#240]
Documentation says `priv: # defaults to not set`. Are there any examples on how this attribute should be populated?

**Comment by aozmen121** [comment]
@geerlingguy or @C0rn3j We've come across an issue where using the following syntax to grant db user privileges:
```
priv: db_schema_name.table_name:SELECT
``` 
however, we get a generic error which doesn't mean anything. Would you mind checking if our privilege syntax is correct?

Would you mind providing examples as well? there doesn't seems to be any documentation around this.
