### ISSUE TITLE
Please consider using Ansible FQCN

### ISSUE THREAD

**Issue by DO1JLR** [geerlingguy/ansible-role-postgresql#245]
Hi @geerlingguy,

Could you consider using fully qualified collection names for your Ansible roles?
It would really help to see faster, why errors like this occur:

```
ERROR! could not resolve module/action 'postgresql_user'. This often indicates a misspelling, a missing collection, or an incorrect module path.
```

And if the role mentions requirements like https://galaxy.ansible.com/community/postgresql that would help too! it could prevent errors like the one above.

**Comment by geerlingguy** [comment]
I assume users are installing ansible the traditional way (e.g. `pip3 install ansible`), which includes all the module mappings as they were pre-collections.

At some point in the future I'll "upgrade" all the roles to FQCN, but for now I want to maintain consistency as that upgrade will require some doing and a bit of dedicated time.

**Comment by davidsielert** [comment]
@geerlingguy  Its worth mentioning that not all Distros (Arch) have the option of installing ansible using pip because it uses the externally managed environment set
