### ISSUE TITLE
RedHat 9 - wrong version number

### ISSUE THREAD

**Issue by kris9854** [geerlingguy/ansible-role-postgresql#252]
Hi @geerlingguy 
The __postgresql_version: "10"
might be wrong as the main postgresql package is version 13. 
The main package is provided in the appstream.

Unless im wrong then just ignore me :)

**Comment by brendon-stephens** [comment]
Agreed. As per [RHEL documentation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/configuring_and_using_database_servers/using-postgresql_configuring-and-using-database-servers#:~:text=RHEL%209%20provides%20PostgreSQL%2013,the%20postgresql%3A15%20module%20stream) the initial version should be v13. 

Added #257 to address this
