### ISSUE TITLE
Prerequisite collection 'community.postgresql' now needed?

### ISSUE THREAD

**Issue by aboschke** [geerlingguy/ansible-role-postgresql#256]
Prior to installing collection 'community.postgresql' was getting this error:

ERROR! couldn't resolve module/action 'postgresql_user'. This often indicates a misspelling, missing collection, or incorrect module path

Perhaps the instructions should be updated to include this now.

**Comment by fthsma** [comment]
Thank you! Installing community.postgresql got me past it!

**Comment by shade-belisar** [comment]
Same problem and solution. I presume this simply requires an update for the readme.
