### ISSUE TITLE
Support modifying the Client Authentication file (`pg_hba.conf`)

### ISSUE THREAD

**Issue by robyoung** [geerlingguy/ansible-role-postgresql#3]
Without this postgres will only accept connections from the local machine.

**Comment by geerlingguy** [comment]
I could've sworn I had added an issue for this already... but I didn't! That's next on my list; the first step was getting the role working in situations when building all-in-one servers (e.g. LAPP stack, for Drupal VM).

**Comment by geerlingguy** [comment]
Also, this file should be relatively easy to template, and it doesn't seem like the default syntax has changed from late 8.x to 9.x, so hopefully it would be compatible across the range of supported versions.

**Comment by geerlingguy** [comment]
Closed through merging PR #4
