### ISSUE TITLE
How to install extensions?

### ISSUE THREAD

**Issue by mirkhamidov** [geerlingguy/ansible-role-postgresql#37]
How make installation extension line
```sql
CREATE EXTENSION IF NOT EXISTS postgis;
```

**Comment by somada141** [comment]
Alternatively you could use the `postgres_ext` module (https://docs.ansible.com/ansible/2.6/modules/postgresql_ext_module.html). I'm preparing a pr to integrate it now

**Comment by AlexGluck** [comment]
@somada141 Cool, thx. Can you add pr and for me?

**Comment by somada141** [comment]
@AlexGluck PR's already there (https://github.com/geerlingguy/ansible-role-postgresql/pull/52), been having some trouble with the CI tests behaving weirdly which I haven't figured out yet.

**Comment by Rendanic** [comment]
This feauture is really interesting.
Is the problem solved?

**Comment by somada141** [comment]
No @Rendanic I haven't figured out what the CI is bothered by, was hoping @geerlingguy would have a looksie

**Comment by antoinebourayne** [comment]
Hi, any update on this ?
