### ISSUE TITLE
Create users before databases

### ISSUE THREAD

**Issue by asharpe** [geerlingguy/ansible-role-postgresql#41]
When databases are created before roles, one cannot set the database to be owned by a role as it does not yet exist.

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/ansible-role-postgresql/pull/31

**Comment by otisranson** [comment]
Hey @asharpe ,
In tasks/main.yaml, have the import_tasks lines in this order:
`# Configure PostgreSQL.
- import_tasks: users.yml
- import_tasks: databases.yml
`
This will create the user first (according to postgres documentation, creating a user is identical to creating a role). Next, in your vars/main.yaml file, have your database and user creation like so:
`postgresql_users:
  - name: dbuser
    login_password: 'turbotopsecret'
postgresql_databases:
  - name: mydb
    owner: dbuser
`

**Comment by geerlingguy** [comment]
This was fixed in https://github.com/geerlingguy/ansible-role-postgresql/pull/31
