### ISSUE TITLE
restart postgresql handler fails

### ISSUE THREAD

**Issue by pyhalov** [geerlingguy/ansible-role-postgresql#56]
```
RUNNING HANDLER [geerlingguy.postgresql : restart postgresql] 
*******************************
fatal: [HOST]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'postgresql_daemon' is undefined\n\nThe error appears to have been in 'PATH_TO_HOME/.ansible/roles/geerlingguy.postgresql/handlers/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: restart postgresql\n  ^ here\n"}
```
One peculiarity is that role including geerlingguy.postgresql  has default setting for postgresql_daemon.
Setting 
```
postgresql_daemon: postgresql
```
in .ansible/roles/geerlingguy.postgresql/defaults/main.yml fixes this.

**Comment by geerlingguy** [comment]
If the daemon is not defined already, then it is picked up by one of the OS/distro-specific files like so: https://github.com/geerlingguy/ansible-role-postgresql/blob/master/vars/RedHat-7.yml#L6

What operating system and version are you using? Is it in this list? https://github.com/geerlingguy/ansible-role-postgresql/tree/master/vars

**Comment by pyhalov** [comment]
It's Ubuntu 18.04.
