### ISSUE TITLE
creating a read-only user

### ISSUE THREAD

**Issue by katmai** [geerlingguy/ansible-role-postgresql#60]
i am trying to create a read only user but i have been looking at the syntax and googling for hours and i still can't figure it out:

i have tried using: 
```
priv: "public:USAGE/ALL:SELECT" #PostgreSQL privileges string in the format: table:priv1,priv2
```
but it errors out with: Invalid privs specified for database: USAGE\n')

i have looked at the postgresql_user and privs page, tried variations but nothing seems to work

can anyone point me in the right direction? just wanna figure out what i am doing wrong.
thanks.

**Comment by andre-integritas** [comment]
where you able to solve it ?

**Comment by katmai** [comment]
yes the syntax is: 

postgresql_objects_privileges:
  - database: dbname
    roles: youruser
    objs: ALL_IN_SCHEMA
    privs: SELECT

**Comment by andre-integritas** [comment]
You are a lifesaver! Thank you

**Comment by epanoff** [comment]
@katmai  How have you resolved the problem?

**Comment by diogopms** [comment]
I was searching in the code, but I can't find any reference to this `postgresql_objects_privileges`. Is this supported by this role?
Thanks

**Comment by geerlingguy** [comment]
@diogopms not that I'm aware of. It looks like that functionality is in this role: https://github.com/natefoo/ansible-postgresql-objects

**Comment by mm3906078** [comment]
Guys, is it this work as well?

  community.postgresql.postgresql_privs:
    database: database
    roles: user
    objs: ALL_IN_SCHEMA
    privs: SELECT
