### ISSUE TITLE
Switch exeucion of adding users with execution of creating db

### ISSUE THREAD

**Issue by fmatuszewski** [geerlingguy/ansible-role-postgresql#63]
# Configure PostgreSQL.
- import_tasks: databases.yml
- import_tasks: users.yml

change to

# Configure PostgreSQL.
- import_tasks: users.yml
- import_tasks: databases.yml

The reason for this is to create user which is needed to use it as the owner of database.

**Comment by mkobel** [comment]
See: #41 / #31

**Comment by geerlingguy** [comment]
This was fixed in https://github.com/geerlingguy/ansible-role-postgresql/pull/31
