### ISSUE TITLE
CentOS 7 fails to install rh-postgresql10

### ISSUE THREAD

**Issue by kalkin** [geerlingguy/ansible-role-postgresql#65]
I'm using Postgresql 10 with CentOS 7. I'm setting the `postgresql_*` variables to get it working. Everything works fine besides two things:
* The “Ensure PostgreSQL database is initialized” task is skipped, because the `PG_VERSION` file already exists
* The initialization command is differnt and is called `postgresql-setup --initdb`.

Thank you for this great module
kalkin-

**Comment by lhoss** [comment]
Can you try using this PR https://github.com/geerlingguy/ansible-role-postgresql/pull/73 ?

**Comment by kalkin** [comment]
@lhoss I'm sorry but I don't have access the machine anymore.

Just try to install it on any CentOS 7 machine.

**Comment by gthieleb** [comment]
@kalkin Is it neccessary to perform `scl enable rh-postgresql96` before running `postgresql-setup`?

**Comment by gthieleb** [comment]
OK got it managed for PG v9.6 using this vars.

inventory:
```
[db]
db.admin.lab ansible_user=root

[db:vars]
postgresql_packages = rh-postgresql96
postgresql_daemon = rh-postgresql96-postgresql
postgresql_bin_path = /opt/rh/rh-postgresql96/root/bin
postgresql_data_dir = /var/opt/rh/rh-postgresql96/lib/pgsql/data
postgresql_config_path = /var/opt/rh/rh-postgresql96/lib/pgsql/data
```

**Comment by bmbouter** [comment]
These vars also worked for me for centos7.

**Comment by lhoss** [comment]
> Can you try using this PR #73 ?

Actually in my old https://github.com/geerlingguy/ansible-role-postgresql/issues/65#issuecomment-491887001,  I confused the PGDG repo/package(s) with the ones from Redhat SCL!
In fact open PR https://github.com/geerlingguy/ansible-role-postgresql/pull/54 is the solution, except that the molecule (lint) build tests are failing there.
My fork contains the same branch incl. lint fixes see: https://github.com/geerlingguy/ansible-role-postgresql/pull/54#issuecomment-531223344
