### ISSUE TITLE
postgres\nsudo: unable to initialize policy plugin

### ISSUE THREAD

**Issue by map1983** [geerlingguy/ansible-role-postgresql#66]
TASK [postgre_install : Ensure PostgreSQL database is initialized.]
"sudo: unknown user: postgres\nsudo: unable to initialize policy plugin\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by tanguybernard** [comment]
Same error if I use:

>  ansible-playbook playbook.yml --check

Remove `--check` option works
