### ISSUE TITLE
Using postgresql_global_config_options is not reversible

### ISSUE THREAD

**Issue by Aethylred** [geerlingguy/ansible-role-postgresql#90]
If you make a mistake setting your listen address by specifying (note address not addresses):

```
postgresql_global_config_options:
  - option: listen_address
    value: "*"
```

Running a play, which then means postgresql does not start, then correct your play and rerun it:

```
postgresql_global_config_options:
  - option: listen_addresses
    value: "*"
```

The broken configuration option _remains_ in the configuration file.

In addition if you manually correct the file and fix the `listen_address` option to say `listen_addresses` the playbook does not detect the duplicate options, and remove one of them.

I'd strongly recommend using templates rather than regex substitutions to create configuration files so that the results are deterministic and reversible.

**Comment by richard-fairthorne** [comment]
The options are not duplicate, so they will not be detected and removed. I'm not the author, but from my perspective, it would make sense to either use an ad-hoc task, or for the author to provide a way to remove a configuration option.

**Comment by Perflyst** [comment]
absent state is supported 
https://github.com/geerlingguy/ansible-role-postgresql/blob/180fac804842610e6bdac05730ed4506dc596629/tasks/configure.yml#L7
```
postgresql_global_config_options:
  - option: listen_address
    value: "*"
    state: absent
```
